name: CI
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clonacion de codigo
        uses: actions/checkout@v4
      - name: Setup Java JDK
        uses: actions/setup-java@v4.2.1
        with: 
          java-version: '8'
          distribution: 'temurin'
      
      - name: Compilacion
        run: |
         mvn package
         
    #  - name: Analisis SonarCloud
        #run: |
         # mvn clean verify org.sonarsource.scanner.maven:sonar-maven-plugin:3.11.0.3922:sonar \
         # -Dsonar.token=${{ secrets.SONAR }} \
         # -Dsonar.host.url=https://sonarcloud.io \
         # -Dsonar.organization=gotelloc \
         # -Dsonar.projectKey=gotelloc_ms-aumento-voto

      - name: Docker Login
        uses: docker/login-action@v3.1.0
        with:
          username: ${{ secrets.DOCKER_USER }} 
          password: ${{ secrets.DOCKER_PASS }} 

     # - name : Set up docker buildx
     #   uses: docker/setup-buildx.action@v3

      - name: Docker build
        run: |
          docker build -t gotelloc/ms-aumento-voto:lastname
      - name: Docker push
        run: |
          docker push gotelloc/ms-aumento-voto:lastname
          
        
          
